In [ ]:
### scope of variables
### nested functions
### recursive functions

In [ ]:
#### scope of the functions

#### Local, Enclosing, Global , Builtin

In [4]:
x=10
def function1():
  x=20
  print("value of x is",x)
function1()

value of x is 20

In [5]:
x = 100

def show():
    x = 50   # Local variable (different from global x)
    print("Inside function:", x)

show()
print("Outside function:", x)

Inside function: 50
Outside function: 100

In [6]:
def add():
    a = 10   # Local variable
    b = 20
    return a + b

print(add())
print(a)

30

NameError: name 'a' is not defined

In [9]:
def outer():
    message = "Hello"   # Enclosing variable
    def inner():
        print(message)  # Access enclosing scope
    inner()
outer()

Hello

In [10]:
message="test"
def outer():
    #message = "Hello"   # Enclosing variable
    def inner():
        print(message)  # Access enclosing scope
    inner()
outer()

test

In [7]:
message="test"
def outer():
    message = "Hello"   # Enclosing variable
    def inner():
        message="abc"
        print(message)  # Access enclosing scope
    inner()
outer()

abc

##first priority local then enclosing then go for global

In [ ]:
#nested function

In [11]:
def function1(x):
  def function2():
    return 'function2'
  def function3():
    return 'function3'
  if x%2==0:
    return function2()
  else:
    return function3()
function1(10)

'function2'

In [1]:
def calculator(a, b):
    def add(): return a + b
    def sub(): return a - b
    def mul(): return a * b
    def div(): return a / b if b != 0 else "Divide by zero"
    return add(), sub(), mul(), div()

print(calculator(10, 5))

(15, 5, 50, 2.0)

In [3]:
def text_processor(sentence):
    def clean(text):
        return text.lower().replace(".", "")
    def count_words(text):
        return len(text.split())

    cleaned = clean(sentence)
    return cleaned, count_words(cleaned)

print(text_processor("Hello, Python World."))

('hello, python world', 3)

In [4]:
def text_processor(sentence):
    def clean(text):
        return text.lower().replace(".", "")
    def count_words(text):
        return len(text.split(","))

    cleaned = clean(sentence)
    return cleaned, count_words(cleaned)

print(text_processor("Hello, Python World."))

('hello, python world', 2)

In [5]:
text="Hello, Python World."
text.split(",")

['Hello', ' Python World.']

In [ ]:
text="hello"
text.split(",")

In [10]:
def power_func(exp):
   def inner(base):
     return base ** exp
   return inner

square = power_func(2)
cube = power_func(3)

print(square(5),cube(2))

25 8

In [ ]:
def voting_system():
    votes = {"A": 0, "B": 0}

    def vote(candidate):
        if candidate in votes:
            votes[candidate] += 1
        return votes

    return vote

vote = voting_system()
print(vote("A"))
print(vote("B"))
print(vote("A"))

In [11]:
def fact(n):
  if n==0:
    return 1
  else:
    return n*fact(n-1)
print(fact(5))

#recursive function

120

In [13]:
#fibonacci series
 #[0,1,1,2,3,5]

def fibonacci(n):
  if n<=1:
    return n
  else:
    return fibonacci(n-1)+fibonacci(n-2)
for i in range(6):
  print(fibonacci(i))

0
1
1
2
3
5

In [14]:
.apply functions

SyntaxError: invalid syntax (ipython-input-754328525.py, line 1)

In [15]:
import pandas as pd
import numpy as np

In [16]:
data = {
    "Name": [
        "Asha Hassan", "Dilli Babu N", "Ekanth Reddy T",
        "Parameshwar D", "Preethi B V", "Shubrati",
        "Sravanthi Veluru", "Supriya Moudgal"
    ],
    "Age": [24, 29, 35, 40, 27, 31, 36, 28],
    "Salary": [48000, 55000, 72000, 80000, 60000, 51000, 75000, 64000],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"]
}

df = pd.DataFrame(data)
print(df)

               Name  Age  Salary Department
0       Asha Hassan   24   48000         HR
1      Dilli Babu N   29   55000         IT
2    Ekanth Reddy T   35   72000    Finance
3     Parameshwar D   40   80000         IT
4       Preethi B V   27   60000         HR
5          Shubrati   31   51000    Finance
6  Sravanthi Veluru   36   75000         IT
7   Supriya Moudgal   28   64000         HR

In [17]:
df

               Name  Age  Salary Department
0       Asha Hassan   24   48000         HR
1      Dilli Babu N   29   55000         IT
2    Ekanth Reddy T   35   72000    Finance
3     Parameshwar D   40   80000         IT
4       Preethi B V   27   60000         HR
5          Shubrati   31   51000    Finance
6  Sravanthi Veluru   36   75000         IT
7   Supriya Moudgal   28   64000         HR

In [18]:
df['Salary'].apply(lambda x:x**2)

0    2304000000
1    3025000000
2    5184000000
3    6400000000
4    3600000000
5    2601000000
6    5625000000
7    4096000000
Name: Salary, dtype: int64

In [19]:
df['Name'].apply(str.isalpha)

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
Name: Name, dtype: bool

In [20]:
df['Salary'].apply(lambda x:x>30000)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
Name: Salary, dtype: bool

In [21]:
df['Salary'].apply(lambda x:"high" if x>50000 else "low")

0     low
1    high
2    high
3    high
4    high
5    high
6    high
7    high
Name: Salary, dtype: object

In [22]:
def tax(row):
    if row["Salary"] > 70000:
        return row["Salary"] * 0.3
    else:
        return row["Salary"] * 0.2

df["Tax"] = df.apply(tax, axis=1)
df

               Name  Age  Salary Department      Tax
0       Asha Hassan   24   48000         HR   9600.0
1      Dilli Babu N   29   55000         IT  11000.0
2    Ekanth Reddy T   35   72000    Finance  21600.0
3     Parameshwar D   40   80000         IT  24000.0
4       Preethi B V   27   60000         HR  12000.0
5          Shubrati   31   51000    Finance  10200.0
6  Sravanthi Veluru   36   75000         IT  22500.0
7   Supriya Moudgal   28   64000         HR  12800.0